spring:
  application:
        name: lottery-system
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lottery_system?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dd.159178280
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail: # 邮件发送配置
    host: smtp.qq.com
    port: 465
    username: 1577045857@qq.com
    password: LMvQZ7dATgPyyaAG # 这里填入获取的 SMTP 授权码
    properties:
      smtp:
        auth: true
        ssl:
          enable: true
  data:
    redis:
      host: localhost
      port: 8888  # 8888 监听 6379 端口
      connect-timeout: 60
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #配置驼峰自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句
  type-handlers-package: com.julien.lotterysystem.mapper.handler # 配置类型处理器包路径（手机号自动加密解密）

logging:
  config: classpath:logback-spring.xml
  file:
    name: lottery-system.log
